mocked_jira_issues = [
    {
        "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
        "id": "11467",
        "self": "https://besnard-consulting.com.atlassian.net/rest/api/latest/issue/11467",
        "key": "EXPROJ-5",
        "fields": {
            "statuscategorychangedate": "2021-05-14T14:42:57.823+0300",
            "issuetype": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issuetype/10042",
                "id": "10042",
                "description": "Tasks track small, distinct pieces of work.",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype",
                "name": "Task",
                "subtask": False,
                "avatarId": 10318,
                "entityId": "db1feb0b-d88f-49c4-ba80-3f5795ef3274",
                "hierarchyLevel": 0,
            },
            "timespent": None,
            "customfield_10074": None,
            "customfield_10030": None,
            "project": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/project/10012",
                "id": "10012",
                "key": "EXPROJ",
                "name": "EXAMPLE PROJECT",
                "projectTypeKey": "software",
                "simplified": True,
                "avatarUrls": {
                    "48x48": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?pid=10012&avatarId=10407",
                    "24x24": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=small&s=small&pid=10012&avatarId=10407",
                    "16x16": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=xsmall&s=xsmall&pid=10012&avatarId=10407",
                    "32x32": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=medium&s=medium&pid=10012&avatarId=10407",
                },
            },
            "fixVersions": [],
            "resolution": None,
            "customfield_10028": None,
            "customfield_10029": None,
            "resolutiondate": None,
            "workratio": -1,
            "watches": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-5/watchers",
                "watchCount": 1,
                "isWatching": True,
            },
            "lastViewed": None,
            "created": "2021-05-14T14:42:57.455+0300",
            "customfield_10020": None,
            "customfield_10021": None,
            "customfield_10022": None,
            "customfield_10023": None,
            "priority": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/priority/3",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/images/icons/priorities/medium.svg",
                "name": "Medium",
                "id": "3",
            },
            "labels": [],
            "customfield_10016": None,
            "customfield_10017": None,
            "customfield_10018": {
                "hasEpicLinkFieldDependency": False,
                "showField": False,
                "nonEditableReason": {
                    "reason": "PLUGIN_LICENSE_ERROR",
                    "message": "The Parent Link is only available to Jira Premium users.",
                },
            },
            "customfield_10019": "0|i0078p:",
            "timeestimate": None,
            "versions": [],
            "issuelinks": [],
            "assignee": None,
            "updated": "2021-05-14T14:42:57.455+0300",
            "status": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/status/10062",
                "description": "",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/",
                "name": "To Do",
                "id": "10062",
                "statusCategory": {
                    "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/statuscategory/2",
                    "id": 2,
                    "key": "new",
                    "colorName": "blue-gray",
                    "name": "To Do",
                },
            },
            "components": [],
            "timeoriginalestimate": None,
            "description": None,
            "customfield_10010": None,
            "customfield_10014": None,
            "customfield_10015": None,
            "customfield_10005": None,
            "customfield_10006": None,
            "customfield_10007": None,
            "security": None,
            "customfield_10008": None,
            "customfield_10009": None,
            "summary": "My Task #2",
            "creator": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=387268476HGDSHDY2u",
                "accountId": "387268476HGDSHDY2u",
                "emailAddress": "example@test.com",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/32",
                },
                "displayName": "Tom J.",
                "active": True,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "reporter": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=387268476HGDSHDY2u",
                "accountId": "387268476HGDSHDY2u",
                "emailAddress": "example@test.com",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/32",
                },
                "displayName": "Tom J.",
                "active": True,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "customfield_10000": "{}",
            "customfield_10001": None,
            "customfield_10002": None,
            "customfield_10047": None,
            "customfield_10003": None,
            "customfield_10048": None,
            "customfield_10004": None,
            "environment": None,
            "duedate": None,
            "progress": {"progress": 0, "total": 0},
            "votes": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-5/votes",
                "votes": 0,
                "hasVoted": False,
            },
        },
    },
    {
        "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
        "id": "11466",
        "self": "https://besnard-consulting.com.atlassian.net/rest/api/latest/issue/11466",
        "key": "EXPROJ-4",
        "fields": {
            "statuscategorychangedate": "2021-05-14T14:42:59.531+0300",
            "issuetype": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issuetype/10042",
                "id": "10042",
                "description": "Tasks track small, distinct pieces of work.",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype",
                "name": "Task",
                "subtask": False,
                "avatarId": 10318,
                "entityId": "db1feb0b-d88f-49c4-ba80-3f5795ef3274",
                "hierarchyLevel": 0,
            },
            "timespent": None,
            "customfield_10074": None,
            "customfield_10030": None,
            "project": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/project/10012",
                "id": "10012",
                "key": "EXPROJ",
                "name": "EXAMPLE PROJECT",
                "projectTypeKey": "software",
                "simplified": True,
                "avatarUrls": {
                    "48x48": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?pid=10012&avatarId=10407",
                    "24x24": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=small&s=small&pid=10012&avatarId=10407",
                    "16x16": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=xsmall&s=xsmall&pid=10012&avatarId=10407",
                    "32x32": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=medium&s=medium&pid=10012&avatarId=10407",
                },
            },
            "fixVersions": [],
            "resolution": None,
            "customfield_10028": None,
            "customfield_10029": None,
            "resolutiondate": None,
            "workratio": -1,
            "lastViewed": "2021-05-14T15:02:46.834+0300",
            "watches": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-4/watchers",
                "watchCount": 1,
                "isWatching": True,
            },
            "created": "2021-05-14T14:27:04.934+0300",
            "customfield_10020": None,
            "customfield_10021": None,
            "customfield_10022": None,
            "customfield_10023": None,
            "priority": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/priority/3",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/images/icons/priorities/medium.svg",
                "name": "Medium",
                "id": "3",
            },
            "labels": [],
            "customfield_10016": None,
            "customfield_10017": None,
            "customfield_10018": {
                "hasEpicLinkFieldDependency": False,
                "showField": False,
                "nonEditableReason": {
                    "reason": "PLUGIN_LICENSE_ERROR",
                    "message": "The Parent Link is only available to Jira Premium users.",
                },
            },
            "customfield_10019": "0|i0078h:",
            "timeestimate": None,
            "versions": [],
            "issuelinks": [],
            "assignee": None,
            "updated": "2021-05-14T14:42:59.530+0300",
            "status": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/status/10065",
                "description": "",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/",
                "name": "To Review",
                "id": "10065",
                "statusCategory": {
                    "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/statuscategory/4",
                    "id": 4,
                    "key": "indeterminate",
                    "colorName": "yellow",
                    "name": "In Progress",
                },
            },
            "components": [],
            "timeoriginalestimate": None,
            "description": None,
            "customfield_10010": None,
            "customfield_10014": None,
            "customfield_10015": None,
            "customfield_10005": None,
            "customfield_10006": None,
            "security": None,
            "customfield_10007": None,
            "customfield_10008": None,
            "customfield_10009": None,
            "summary": "My Task #1",
            "creator": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=387268476HGDSHDY2u",
                "accountId": "387268476HGDSHDY2u",
                "emailAddress": "example@test.com",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/32",
                },
                "displayName": "Tom J.",
                "active": True,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "reporter": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=387268476HGDSHDY2u",
                "accountId": "387268476HGDSHDY2u",
                "emailAddress": "example@test.com",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/387268476HGDSHDY2u/0871952a-d260-4464-9fe9-06bd0e7d550c/32",
                },
                "displayName": "Tom J.",
                "active": True,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "customfield_10000": "{}",
            "customfield_10001": None,
            "customfield_10002": None,
            "customfield_10047": None,
            "customfield_10003": None,
            "customfield_10004": None,
            "customfield_10048": None,
            "environment": None,
            "duedate": None,
            "progress": {"progress": 0, "total": 0},
            "votes": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-4/votes",
                "votes": 0,
                "hasVoted": False,
            },
        },
    },
    {
        "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
        "id": "10853",
        "self": "https://besnard-consulting.com.atlassian.net/rest/api/latest/issue/10853",
        "key": "EXPROJ-3",
        "fields": {
            "statuscategorychangedate": "2020-11-13T08:41:40.518+0200",
            "issuetype": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issuetype/10042",
                "id": "10042",
                "description": "Tasks track small, distinct pieces of work.",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype",
                "name": "Task",
                "subtask": False,
                "avatarId": 10318,
                "entityId": "db1feb0b-d88f-49c4-ba80-3f5795ef3274",
                "hierarchyLevel": 0,
            },
            "timespent": None,
            "customfield_10030": None,
            "customfield_10074": None,
            "project": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/project/10012",
                "id": "10012",
                "key": "EXPROJ",
                "name": "EXAMPLE PROJECT",
                "projectTypeKey": "software",
                "simplified": True,
                "avatarUrls": {
                    "48x48": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?pid=10012&avatarId=10407",
                    "24x24": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=small&s=small&pid=10012&avatarId=10407",
                    "16x16": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=xsmall&s=xsmall&pid=10012&avatarId=10407",
                    "32x32": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=medium&s=medium&pid=10012&avatarId=10407",
                },
            },
            "fixVersions": [],
            "resolution": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/resolution/10000",
                "id": "10000",
                "description": "Work has been completed on this issue.",
                "name": "Done",
            },
            "customfield_10028": None,
            "customfield_10029": None,
            "resolutiondate": "2020-11-13T08:41:40.513+0200",
            "workratio": -1,
            "lastViewed": None,
            "watches": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-3/watchers",
                "watchCount": 2,
                "isWatching": False,
            },
            "created": "2020-10-07T08:05:41.580+0300",
            "customfield_10020": None,
            "customfield_10021": None,
            "customfield_10022": "2020-10-07T08:09:38.478+0300",
            "customfield_10023": "10062_*:*_1_*:*_218619_*|*_10064_*:*_1_*:*_0_*|*_10063_*:*_6_*:*_3202070493_*|*_10065_*:*_2_*:*_269844",
            "priority": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/priority/3",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/images/icons/priorities/medium.svg",
                "name": "Medium",
                "id": "3",
            },
            "labels": [],
            "customfield_10016": None,
            "customfield_10017": None,
            "customfield_10018": {
                "hasEpicLinkFieldDependency": False,
                "showField": False,
                "nonEditableReason": {
                    "reason": "PLUGIN_LICENSE_ERROR",
                    "message": "The Parent Link is only available to Jira Premium users.",
                },
            },
            "customfield_10019": "0|i0048t:",
            "timeestimate": None,
            "versions": [],
            "issuelinks": [],
            "assignee": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=UIOYFD343434FSF",
                "accountId": "UIOYFD343434FSF",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/32",
                },
                "displayName": "John Doe",
                "active": False,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "updated": "2020-11-13T08:41:40.517+0200",
            "status": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/status/10064",
                "description": "",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/",
                "name": "Done Done (Merged)",
                "id": "10064",
                "statusCategory": {
                    "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/statuscategory/3",
                    "id": 3,
                    "key": "done",
                    "colorName": "green",
                    "name": "Done",
                },
            },
            "components": [],
            "timeoriginalestimate": None,
            "description": None,
            "customfield_10010": None,
            "customfield_10014": None,
            "customfield_10015": None,
            "customfield_10005": None,
            "customfield_10006": None,
            "security": None,
            "customfield_10007": None,
            "customfield_10008": None,
            "customfield_10009": None,
            "summary": "Polish CI file",
            "creator": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=UIOYFD343434FSF",
                "accountId": "UIOYFD343434FSF",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/32",
                },
                "displayName": "John Doe",
                "active": False,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "reporter": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=UIOYFD343434FSF",
                "accountId": "UIOYFD343434FSF",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/32",
                },
                "displayName": "John Doe",
                "active": False,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "customfield_10000": "{}",
            "customfield_10001": None,
            "customfield_10002": None,
            "customfield_10003": None,
            "customfield_10047": None,
            "customfield_10048": None,
            "customfield_10004": None,
            "environment": None,
            "duedate": None,
            "progress": {"progress": 0, "total": 0},
            "votes": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-3/votes",
                "votes": 0,
                "hasVoted": False,
            },
        },
    },
    {
        "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
        "id": "10828",
        "self": "https://besnard-consulting.com.atlassian.net/rest/api/latest/issue/10828",
        "key": "EXPROJ-2",
        "fields": {
            "statuscategorychangedate": "2020-11-13T08:41:42.003+0200",
            "issuetype": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issuetype/10042",
                "id": "10042",
                "description": "Tasks track small, distinct pieces of work.",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype",
                "name": "Task",
                "subtask": False,
                "avatarId": 10318,
                "entityId": "db1feb0b-d88f-49c4-ba80-3f5795ef3274",
                "hierarchyLevel": 0,
            },
            "timespent": None,
            "customfield_10030": None,
            "customfield_10074": None,
            "project": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/project/10012",
                "id": "10012",
                "key": "EXPROJ",
                "name": "EXAMPLE PROJECT",
                "projectTypeKey": "software",
                "simplified": True,
                "avatarUrls": {
                    "48x48": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?pid=10012&avatarId=10407",
                    "24x24": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=small&s=small&pid=10012&avatarId=10407",
                    "16x16": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=xsmall&s=xsmall&pid=10012&avatarId=10407",
                    "32x32": "https://besnard-consulting.com.atlassian.net/secure/projectavatar?size=medium&s=medium&pid=10012&avatarId=10407",
                },
            },
            "fixVersions": [],
            "resolution": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/resolution/10000",
                "id": "10000",
                "description": "Work has been completed on this issue.",
                "name": "Done",
            },
            "customfield_10028": None,
            "customfield_10029": None,
            "resolutiondate": "2020-11-13T08:41:41.998+0200",
            "workratio": -1,
            "lastViewed": None,
            "watches": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-2/watchers",
                "watchCount": 2,
                "isWatching": False,
            },
            "created": "2020-10-02T08:23:03.032+0300",
            "customfield_10020": None,
            "customfield_10021": None,
            "customfield_10022": "2020-10-05T14:06:37.961+0300",
            "customfield_10023": "10062_*:*_19_*:*_3125943826_*|*_10064_*:*_3_*:*_59801693_*|*_10063_*:*_22_*:*_298728523_*|*_10065_*:*_7_*:*_149044947",
            "priority": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/priority/3",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/images/icons/priorities/medium.svg",
                "name": "Medium",
                "id": "3",
            },
            "labels": [],
            "customfield_10016": None,
            "customfield_10017": None,
            "customfield_10018": {
                "hasEpicLinkFieldDependency": False,
                "showField": False,
                "nonEditableReason": {
                    "reason": "PLUGIN_LICENSE_ERROR",
                    "message": "The Parent Link is only available to Jira Premium users.",
                },
            },
            "customfield_10019": "0|i0048h:",
            "timeestimate": None,
            "versions": [],
            "issuelinks": [],
            "assignee": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=UIOYFD343434FSF",
                "accountId": "UIOYFD343434FSF",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/32",
                },
                "displayName": "John Doe",
                "active": False,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "updated": "2020-11-13T08:41:42.264+0200",
            "status": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/status/10064",
                "description": "",
                "iconUrl": "https://besnard-consulting.com.atlassian.net/",
                "name": "Done Done (Merged)",
                "id": "10064",
                "statusCategory": {
                    "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/statuscategory/3",
                    "id": 3,
                    "key": "done",
                    "colorName": "green",
                    "name": "Done",
                },
            },
            "components": [],
            "timeoriginalestimate": None,
            "description": "This is just a test ticket.",
            "customfield_10010": None,
            "customfield_10014": None,
            "customfield_10015": None,
            "customfield_10005": None,
            "customfield_10006": None,
            "security": None,
            "customfield_10007": None,
            "customfield_10008": None,
            "customfield_10009": None,
            "summary": "Polish README file",
            "creator": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=UIOYFD343434FSF",
                "accountId": "UIOYFD343434FSF",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/32",
                },
                "displayName": "John Doe",
                "active": False,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "reporter": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/user?accountId=UIOYFD343434FSF",
                "accountId": "UIOYFD343434FSF",
                "avatarUrls": {
                    "48x48": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/48",
                    "24x24": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/24",
                    "16x16": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/16",
                    "32x32": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/UIOYFD343434FSF/1ebb9879-34df-4e23-a809-9e48b120bce1/32",
                },
                "displayName": "John Doe",
                "active": False,
                "timeZone": "Europe/London",
                "accountType": "atlassian",
            },
            "customfield_10000": "{}",
            "customfield_10001": None,
            "customfield_10002": None,
            "customfield_10003": None,
            "customfield_10047": None,
            "customfield_10048": None,
            "customfield_10004": None,
            "environment": None,
            "duedate": None,
            "progress": {"progress": 0, "total": 0},
            "votes": {
                "self": "https://besnard-consulting.com.atlassian.net/rest/api/2/issue/EXPROJ-2/votes",
                "votes": 0,
                "hasVoted": False,
            },
        },
    },
]
